.PHONY: clean All

All:
	@echo "----------Building project:[ WordSearch - Debug ]----------"
	@cd "WordSearch" && "$(MAKE)" -f  "WordSearch.mk"
clean:
	@echo "----------Cleaning project:[ WordSearch - Debug ]----------"
	@cd "WordSearch" && "$(MAKE)" -f  "WordSearch.mk" clean
